markdown:         rdiscount
highlighter: pygments
paginate:         4

title:            Sharon's Blog
url:              http://sharonlx.github.io
feed:             /atom.xml
author:
    name:         Sharon
    email:        ixuan.lee@gmail.com
    disqus:       leexuanr
description:      "关于前端技术的杂博 "
disqus:       leexuanr

about: 			  "热爱生活、热爱技术、热爱运动的小姑娘"
follow:
    github:       https://github.com/sharonlx

markdown: redcarpet
style: 			  /css/style.css
blogName: 		  D大调交响乐
blogDesc: 		  念念不忘 必有回响